# Week 1 (Day 1–7) – Linear Regression + Stats
Tasks: 
- [x] Install Python packages: numpy, pandas, matplotlib, scikit-learn
- [X] Load dataset (Default of Credit Card Clients)
- [X] Explore dataset: missing values, column types, basic stats
- [ ] Train linear regression, print coefficients
- [ ] Plot predicted vs actual values

Reflection: 
- What does each coefficient mean?
- How does partial derivitave connect to weight updates?

## Fetching and Loading the Dataset

After experimenting with the data set I chose to work with a CSV file

In [25]:
import pandas as pd

df  = pd.read_csv("datasets/defaults.csv")

df.head()

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

Top haeder has the featueres while the second row has the column names. Somehow the df.head() doesn't count the first row as row 0 and also doesnt count row 2 as row 1

- `X1 - X23` indicates the featuers based on the documentation
- `ID` is the ID of the person
- `Y` is the target value

Since the first row is primarily for features I willl map the features and set the header to the second row header = 1

In [30]:
df = pd.read_csv("datasets/defaults.csv", header=1)

feature_mapping = {
    'X1': 'LIMIT_BAL',
    'X2': 'SEX',
    'X3': 'EDUCATION',
    'X4': 'MARRIAGE',
    'X5': 'AGE',
    'X6': 'PAY_0',
    'X7': 'PAY_2',
    'X8': 'PAY_3',
    'X9': 'PAY_4',
    'X10': 'PAY_5',
    'X11': 'PAY_6',
    'X12': 'BILL_AMT1',
    'X13': 'BILL_AMT2',
    'X14': 'BILL_AMT3',
    'X15': 'BILL_AMT4',
    'X16': 'BILL_AMT5',
    'X17': 'BILL_AMT6',
    'X18': 'PAY_AMT1',
    'X19': 'PAY_AMT2',
    'X20': 'PAY_AMT3',
    'X21': 'PAY_AMT4',
    'X22': 'PAY_AMT5',
    'X23': 'PAY_AMT6',
    'Y': 'default_payment_next_month'
}

df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

Kept the features for reference if needed and now the df feels more natural.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

Based on df.info() It seems that I am entirelly working on int values

In [33]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

No null values in any row

In [38]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables:
- X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.
- X2: `Gender` (1 = male; 2 = female).
- X3: `Education` (1 = graduate school; 2 = university; 3 = high school; 4 = others).
- X4: `Marital status` (1 = married; 2 = single; 3 = others).
- X5: `Age` (year).
- X6 - X11: History of past payment. 
    - X6 = the repayment status in September, 2005; 
    - X7 = the repayment status in August, 2005; . . .;
    - X11 = the repayment status in April, 2005. 
    
    The measurement scale for the repayment status is: 
    - -1 = pay duly; 
        - "Pay Duly" refers to the process of settling patient bills for services received at Duly Health and Care
    - 1 = payment delay for one month; 
    - 2 = payment delay for two months; . . .; 
    - 8 = payment delay for eight months; 
    - 9 = payment delay for nine months and above.
- X12-X17: Amount of bill statement (NT dollar). 
    - X12 = amount of bill statement in September, 2005; 
    - X13 = amount of bill statement in August, 2005; . . .; 
    - X17 = amount of bill statement in April, 2005. 
- X18-X23: Amount of previous payment (NT dollar). 
    - X18 = amount paid in September, 2005; 
    - X19 = amount paid in August, 2005; . . .;
    - X23 = amount paid in April, 2005.

With this the Dataset is fully understandable and has been verified that there is no strange parts of the data.

# Training Regressions
Resource: [Linear Regression in Python](https://realpython.com/linear-regression-in-python/)

After studying the above resource I've relearend that regressions are just lines of best fit and that there are multiple forms

## What is this dataset good for?
The dataset is good for:
- Logistic Regression
    - Logistic Regression is used when the target is binary
    - Instead of predicting y directly it predicts: P(Y = 1|X)
    - Biggest Difference in Logistic regression is the Sigmoid function
        - The regression wraps the linear equation isnide a sigmoid function
        $\sigma(z) = \frac{1}{1 + e^{-z}}$
        - WHere: $y = b_0 + b_1x_1 + b_2x_2 + \dots + b_nx_n$
    - The sigmoid: keeps the output between 0 and 1 giving a true probability

- Random Forest
    - Instead of one decision tree I am building muany decision trees
    - Each tree:
        - Mkaes its own prediciton
        - looks at random subsets of data
        - looks at random subsets of features
    - Then:
        - Final prediction = majority vote (classification)
    - This is better because an indiviudal tree would overfit
    - A forest averages them → reducing overfitting.
- XGBoost (Extreme Gradient Boosting)
    - It builds trees sequentially unlike Random forest that builds them sequentially
        - Each new tree focuses on correcting mistakes of previous trees
- SVM
    - Tries to find the best boundary that separates two classes. 
    - Like plotting defaulters vs non-defaulters
    - Finds the line (or hyperplane) that:
        - Maximizes the margin between the two classes.
    - Margin = distance between boundary and closest points.
    - Powerful but less scalable than tree-based methods and is more math heavy
- Neural Networks
    - Mimics neurons
        - Takes inputs
        - Multiply by weights
        - Apply activation functions
        - Stack multiple layers.
    - Reallly good for nonlinear patterns

And even more importantly:
- Studying class imbalance
    - Class imbalance is when there is one side that is very imbalanced, this imbalance can allow for the model to get away with predicting the majority or the bigger probability, making it good at finding a non -defaulter rather than being good at finding a defaulter.
- Understanding feature importance
- Learning ROC/AUC
    - ROC Curve  (ROC = Receiver Operating Characteristic)
        - It plots: True Positive Rate (Recall) vs False Positive Rate
    - AUC (Area Under the Curve)
        - Tells you how well the model separates the two classes.
- Learning confusion matrices

|            | Predicted No | Predicted Yes |
| ---------- | ------------ | ------------- |
| Actual No  | TN           | FP            |
| Actual Yes | FN           | TP            |

- Learning precision vs recall tradeoffs
    - Precission: Of the people predicted to default, how many actually defaulted
    - Recall: Of all actual defaulters: How many did we catch?
        - In credit risk, recall is usually very important.

## Questions to ask myself (Data Science questions)
1. What is my target? (Continuous or categorical)
    - This dataset is categorical: I am after a True or false outcome (1,0)
2. What is the problem facing? (Regression or classification)
    - This problem is facing Classification
3. What metric matters most? (Accuracy? Recall? AUC?)
    - What matters is Recall

In [40]:
target_col = next(
    col for col in ["default payment next month", "default_payment_next_month", "Y"]
    if col in df.columns
)

total_accounts = len(df)
defaulted_accounts = (df[target_col] == 1).sum()
default_rate = (defaulted_accounts / total_accounts) * 100

print(f"Total accounts: {total_accounts}")
print(f"Defaulted accounts: {defaulted_accounts}")
print(f"Default rate: {default_rate:.2f}%")

Total accounts: 30000
Defaulted accounts: 6636
Default rate: 22.12%

Paying attention to the fact that the default rate is only around 20% it presents the possibility of having a bad model that trys predicting who won't default and because the presentage of non defaults is 78% it will think that it is highly accurate but in reality the model is just useless.

When one class is smaller than the other the model may become biased toward the majority class

It learns:

    “I can be mostly right just by predicting no default.”

### Why This Is Dangerous in Credit Risk

Missing a defaulter (False Negative) means:

- You approve a risky customer
- They default
- You lose money

So for banks:
- Recall for defaulters is often more important than raw accuracy.

The problem isn’t just:

    “We don’t have enough examples.”

The problem is:

    The model is incentivized to ignore the minority class unless we intervene.

### How We Fix It

Use better metrics:
- Recall
- Precision
- F1 Score
- ROC/AUC

Adjust class weights:
``` python
    LogisticRegression(class_weight='balanced')
```

# Citation
Yeh, I. (2009). Default of Credit Card Clients [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C55S3H.